### ISSUE TITLE
Schemas Todo

### ISSUE THREAD

**Issue by mouimet-infinisoft** [Infinisoft-inc/kitchen#24]
- [x] Move to storage.infini-soft.com
- [x] Change links in schema
- [x] refactor ic-editor to use new storage and use configuration from now on
- [x] refactor CLI with options and config for schema resolving, no more hardcoded values
- [x] test everything with micro-callback app
  - [x] generate API
  - [x] Services
  - [x] SDK

**Comment by mouimet-infinisoft** [comment]
Everything tested on blog use case and working
